apiVersion: v1
kind: Service
metadata:
  name: mymavenapp-service
spec:
  selector:
    app: mymavenapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
      nodePort: 32325  # External port
  type: NodePort
